
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    container_name: lms_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "2006:80"
    networks:
      - lmsnet
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

  mariadb:
    image: mariadb:10.11
    container_name: lms_mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lms_blog
      MYSQL_ROOT_PASSWORD: root_pass_change_me
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - lmsnet

  redis:
    image: redis:7-alpine
    container_name: lms_redis
    restart: unless-stopped
    networks:
      - lmsnet
    ports:
      - "6379:6379"

  # Worker untuk queue (kirim email, dll)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - lmsnet
    depends_on:
      - app
      - redis
    command: php artisan queue:work --tries=3 --timeout=90
    env_file:
      - .env

networks:
  lmsnet:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
